//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ideka.HitboxView {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ideka.HitboxView.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Ping.
        /// </summary>
        internal static string SettingGamePing {
            get {
                return ResourceManager.GetString("SettingGamePing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this to your average ping (currently this cannot be automatically determined)..
        /// </summary>
        internal static string SettingGamePingText {
            get {
                return ResourceManager.GetString("SettingGamePingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping must be a valid integer between {0} and {1}.
        /// </summary>
        internal static string SettingGamePingValidation {
            get {
                return ResourceManager.GetString("SettingGamePingValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitbox Color.
        /// </summary>
        internal static string SettingHitboxColor {
            get {
                return ResourceManager.GetString("SettingHitboxColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of the hitbox..
        /// </summary>
        internal static string SettingHitboxColorText {
            get {
                return ResourceManager.GetString("SettingHitboxColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitbox Smoothing.
        /// </summary>
        internal static string SettingHitboxSmoothing {
            get {
                return ResourceManager.GetString("SettingHitboxSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the hitbox smoothly, interpolating between the game&apos;s reported values..
        /// </summary>
        internal static string SettingHitboxSmoothingText {
            get {
                return ResourceManager.GetString("SettingHitboxSmoothingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hitbox.
        /// </summary>
        internal static string SettingHitboxVisible {
            get {
                return ResourceManager.GetString("SettingHitboxVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable to hide the hitbox..
        /// </summary>
        internal static string SettingHitboxVisibleText {
            get {
                return ResourceManager.GetString("SettingHitboxVisibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Hitbox.
        /// </summary>
        internal static string SettingToggleHitboxKey {
            get {
                return ResourceManager.GetString("SettingToggleHitboxKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle hitbox visibility..
        /// </summary>
        internal static string SettingToggleHitboxKeyText {
            get {
                return ResourceManager.GetString("SettingToggleHitboxKeyText", resourceCulture);
            }
        }
    }
}
